# Generated by Django 5.0.2 on 2024-03-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodle', '0002_mealevent_score_alter_foodle_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foodle',
        ),
    ]
