# Generated by Django 5.0.2 on 2024-02-28 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientRatings',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_title', models.CharField(max_length=200)),
                ('recipe_ingredients', models.CharField(max_length=200)),
                ('preparation', models.TextField()),
                ('prep_time', models.IntegerField(default=0)),
                ('serves_num', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
