# Generated by Django 5.0.2 on 2024-02-28 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientRatings',
            new_name='IngredientRating',
        ),
    ]
