# Generated by Django 5.0.2 on 2024-02-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_ingredientratings_ingredientrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='co2_per_portion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serves_num',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
