# Generated by Django 5.0.2 on 2024-02-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_co2_per_portion_recipe_sulphates_per_portion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.TextField(),
        ),
    ]
