# Generated by Django 5.0.2 on 2024-03-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrating',
            name='allergen',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
