# Generated by Django 5.0.2 on 2024-03-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_ingredientrating_allergen'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergens',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
