# Generated by Django 5.0.2 on 2024-03-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='allergens',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
